#!/usr/bin/env bash

if [ "${DOCKER_TAG}" != "stable" ] && [ "${DOCKER_TAG}" != "testing" ] && [ "${DOCKER_TAG}" != "vaapi" ]; then
	DOCKER_TAG="latest"
fi

docker build \
		--build-arg BASE_IMAGE_TAG=${DOCKER_TAG} \
		-t ${IMAGE_NAME} .
