#!/usr/bin/with-contenv bash

# check if EPG2XML_VER exist
if [[ -z "${EPG2XML_VER}" ]]; then
	exit 0
fi

# make folder
[[ ! -d "/epg2xml" ]] && mkdir /epg2xml

# download and update relevant scripts
wget -q "https://github.com/wonipapa/epg2xml/archive/v${EPG2XML_VER}.tar.gz" -P /tmp && \
	cd /tmp && tar -xzf "v${EPG2XML_VER}.tar.gz"
mv "/tmp/epg2xml-${EPG2XML_VER}"/*.php /epg2xml/
mv "/tmp/epg2xml-${EPG2XML_VER}"/Channel.json /epg2xml/

# also update epg2xml.json files if not exist
[[ ! -f /epg2xml/epg2xml.json ]] && \
	mv "/tmp/epg2xml-${EPG2XML_VER}"/epg2xml.json /epg2xml/

# permissions
chown -R abc:abc \
	/epg2xml

# cleanup
rm -rf /tmp/*
