#!/usr/bin/with-contenv bash

[[ -z "${FFMPEGBIN_VER}" ]] && \
wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -P /tmp && \
apk add --no-cache xz && \
cd /tmp && \
xz -d ffmpeg-release-64bit-static.tar.xz && \
tar xvf ffmpeg-release-64bit-static.tar && \
cp "/tmp/ffmpeg-${FFMPEGBIN_VER}-64bit-static/ffmpeg" /usr/bin/ffmpeg && \
rm -rf /tmp/*
