#!/usr/bin/with-contenv bash

# check if FFMPEGBIN_VER exist
if [[ -z "${FFMPEGBIN_VER}" ]]; then
	exit 0
fi

[[ "${FFMPEGBIN_VER}" == "latest" ]] && \
wget -q https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -P /tmp && \
apk add --no-cache --quiet xz && \
cd /tmp && \
xz -d ffmpeg-release-64bit-static.tar.xz && \
tar xf ffmpeg-release-64bit-static.tar && \
find . -name ffmpeg -exec cp {} /usr/bin \; && \
echo "$(ls | grep -m 1 "ffmpeg") is installed" && \
rm -rf /tmp/*

