#!/usr/bin/with-contenv bash

# check if TVH_URL exist
if [[ -z "${TVH_URL}" ]]; then
	exit 0
fi

# # install tvhProxy and its dependencies
# apk add --no-cache --quiet git gcc python-dev musl-dev py-pip
# pip install --upgrade --quiet pip

mkdir -p /tvhProxy
wget -q "https://raw.githubusercontent.com/jkaberg/tvhProxy/master/tvhProxy.py" -P /tvhProxy
# wget -q "https://raw.githubusercontent.com/jkaberg/tvhProxy/master/requirements.txt" -P /tvhProxy

# permissions
chown -R abc:abc \
	/tvhProxy

# cd /tvhProxy && pip install -q -r requirements.txt
